# Ecosystem Sync Configuration
# Using BetaHuhn/repo-file-sync-action
#
# Three Sync Types:
# 1. always-sync: Files every repo MUST always have (auto-updates, versions in git history)
# 2. initial-only: Files repos MUST start with (one-time sync, versions in repo as patches)
# 3. patch-sync: Optional files repos CAN adopt (opt-in, multiple versions available)
#
# See docs/SYNC-FILE-VERSIONING.md for complete versioning policy

# =============================================================================
# ORG .GITHUB REPOS - Settings inheritance
# =============================================================================
jbcom/.github:
  - source: sync-files/always-sync/global/.github/
    dest: .github/

arcade-cabinet/.github:
  - source: sync-files/always-sync/global/.github/
    dest: .github/

agentic-dev-library/.github:
  - source: sync-files/always-sync/global/.github/
    dest: .github/

extended-data-library/.github:
  - source: sync-files/always-sync/global/.github/
    dest: .github/

strata-game-library/.github:
  - source: sync-files/always-sync/global/.github/
    dest: .github/

# =============================================================================
# JBCOM ORG REPOS
# =============================================================================
jbcom/jbcom.github.io:
  - source: sync-files/always-sync/global/
    dest: ./

# =============================================================================
# ARCADE-CABINET ORG REPOS
# =============================================================================
arcade-cabinet/arcade-cabinet.github.io:
  - source: sync-files/always-sync/global/
    dest: ./

arcade-cabinet/protocol-silent-night:
  - source: sync-files/always-sync/global/
    dest: ./

arcade-cabinet/Beppo-Laughs:
  - source: sync-files/always-sync/global/
    dest: ./

arcade-cabinet/sky-hats:
  - source: sync-files/always-sync/global/
    dest: ./

arcade-cabinet/otterblade-odyssey:
  - source: sync-files/always-sync/global/
    dest: ./

arcade-cabinet/rivers-of-reckoning:
  - source: sync-files/always-sync/global/
    dest: ./

arcade-cabinet/realm-walker:
  - source: sync-files/always-sync/global/
    dest: ./

arcade-cabinet/otter-river-rush:
  - source: sync-files/always-sync/global/
    dest: ./

arcade-cabinet/otter-elite-force:
  - source: sync-files/always-sync/global/
    dest: ./

arcade-cabinet/ebb-and-bloom:
  - source: sync-files/always-sync/global/
    dest: ./

arcade-cabinet/dragons-labyrinth:
  - source: sync-files/always-sync/global/
    dest: ./

arcade-cabinet/rivermarsh:
  - source: sync-files/always-sync/global/
    dest: ./

arcade-cabinet/cosmic-cults:
  - source: sync-files/always-sync/global/
    dest: ./

arcade-cabinet/echoes-of-beastlight:
  - source: sync-files/always-sync/global/
    dest: ./

# =============================================================================
# AGENTIC-DEV-LIBRARY ORG REPOS
# =============================================================================
agentic-dev-library/agentic-dev-library.github.io:
  - source: sync-files/always-sync/global/
    dest: ./

agentic-dev-library/triage:
  - source: sync-files/always-sync/global/
    dest: ./

agentic-dev-library/game-generator:
  - source: sync-files/always-sync/global/
    dest: ./

agentic-dev-library/crew:
  - source: sync-files/always-sync/global/
    dest: ./

agentic-dev-library/control:
  - source: sync-files/always-sync/global/
    dest: ./

agentic-dev-library/asset-pipeline:
  - source: sync-files/always-sync/global/
    dest: ./

# =============================================================================
# EXTENDED-DATA-LIBRARY ORG REPOS
# =============================================================================
extended-data-library/extended-data-library.github.io:
  - source: sync-files/always-sync/global/
    dest: ./

extended-data-library/vendor-connectors:
  - source: sync-files/always-sync/global/
    dest: ./

extended-data-library/logging:
  - source: sync-files/always-sync/global/
    dest: ./

extended-data-library/inputs:
  - source: sync-files/always-sync/global/
    dest: ./

extended-data-library/core:
  - source: sync-files/always-sync/global/
    dest: ./

extended-data-library/secretssync:
  - source: sync-files/always-sync/global/
    dest: ./

# =============================================================================
# STRATA-GAME-LIBRARY ORG REPOS
# =============================================================================
strata-game-library/strata-game-library.github.io:
  - source: sync-files/always-sync/global/
    dest: ./

strata-game-library/audio-synth:
  - source: sync-files/always-sync/global/
    dest: ./

strata-game-library/typescript-tutor:
  - source: sync-files/always-sync/global/
    dest: ./

strata-game-library/shaders:
  - source: sync-files/always-sync/global/
    dest: ./

strata-game-library/react-native-plugin:
  - source: sync-files/always-sync/global/
    dest: ./

strata-game-library/presets:
  - source: sync-files/always-sync/global/
    dest: ./

strata-game-library/model-synth:
  - source: sync-files/always-sync/global/
    dest: ./

strata-game-library/examples:
  - source: sync-files/always-sync/global/
    dest: ./

strata-game-library/core:
  - source: sync-files/always-sync/global/
    dest: ./

strata-game-library/capacitor-plugin:
  - source: sync-files/always-sync/global/
    dest: ./

# =============================================================================
# LANGUAGE PROFILES - Add specific repos as discovered
# =============================================================================

# Python repos - docs/conf.py, docs tooling (8 files)
# Uncomment and add repo names as discovered:
# jbcom/python-project:
#   - source: sync-files/always-sync/global/
#     dest: ./
#   - source: sync-files/always-sync/python/
#     dest: ./

# Node.js repos - typedoc config (4 files)
# jbcom/nodejs-project:
#   - source: sync-files/always-sync/global/
#     dest: ./
#   - source: sync-files/always-sync/nodejs/
#     dest: ./

# Go repos - Hugo site, doc2go (13 files)
# jbcom/go-project:
#   - source: sync-files/always-sync/global/
#     dest: ./
#   - source: sync-files/always-sync/go/
#     dest: ./

# Terraform repos - docs README (1 file)
# jbcom/terraform-project:
#   - source: sync-files/always-sync/global/
#     dest: ./
#   - source: sync-files/always-sync/terraform/
#     dest: ./

# Rust repos - rustdoc styling (2 files)
# jbcom/rust-project:
#   - source: sync-files/always-sync/global/
#     dest: ./
#   - source: sync-files/always-sync/rust/
#     dest: ./

# =============================================================================
# INITIAL-ONLY: Starter files (sync once, then repos own them)
# =============================================================================
# Example:
# your-org/new-repo:
#   - source: sync-files/initial-only/global/
#     dest: ./
#     labels: [initial-only, manual-review]

# =============================================================================
# PATCH-SYNC: Optional files (repos opt-in to specific versions)
# =============================================================================
# Example:
# your-org/repo-that-wants-feature:
#   - source: sync-files/patch-sync/global/advanced-ci-v2.0.0.yml
#     dest: .github/workflows/advanced-ci.yml
#     labels: [patch-sync, optional]

# =============================================================================
# EXCEPTIONS: Special cases and custom configurations
# =============================================================================
