# Initial-Only Sync Configuration
# These files are synced ONLY IF THEY DON'T EXIST in the target repository
# Use for templates that repos can customize after initial setup
#
# Documentation: https://github.com/BetaHuhn/repo-file-sync-action
# Key setting: replace: false - prevents overwriting existing files

group:
  # ============================================================================
  # Initial-only files - only create if missing
  # ============================================================================
  - files:
      # Cursor environment config
      - source: repository-files/initial-only/.cursor/Dockerfile
        dest: .cursor/Dockerfile
        replace: false
      - source: repository-files/initial-only/.cursor/environment.json
        dest: .cursor/environment.json
        replace: false
      # Dependabot config (repos can customize)
      - source: repository-files/initial-only/.github/dependabot.yml
        dest: .github/dependabot.yml
        replace: false
      # Security policy
      - source: repository-files/initial-only/.github/SECURITY.md
        dest: .github/SECURITY.md
        replace: false
      # Issue templates
      - source: repository-files/initial-only/.github/ISSUE_TEMPLATE/bug.yml
        dest: .github/ISSUE_TEMPLATE/bug.yml
        replace: false
      - source: repository-files/initial-only/.github/ISSUE_TEMPLATE/feature.yml
        dest: .github/ISSUE_TEMPLATE/feature.yml
        replace: false
      - source: repository-files/initial-only/.github/ISSUE_TEMPLATE/config.yml
        dest: .github/ISSUE_TEMPLATE/config.yml
        replace: false
      # Documentation workflow
      - source: repository-files/initial-only/.github/workflows/docs.yml
        dest: .github/workflows/docs.yml
        replace: false
      # AI agent instructions (repos can customize)
      - source: repository-files/initial-only/AGENTS.md
        dest: AGENTS.md
        replace: false
      - source: repository-files/initial-only/CLAUDE.md
        dest: CLAUDE.md
        replace: false
    repos: |
      jbcom/python-agentic-crew
      jbcom/python-agentic-game-development
      jbcom/python-directed-inputs-class
      jbcom/python-extended-data-types
      jbcom/python-lifecyclelogging
      jbcom/python-vendor-connectors
      jbcom/jbcom.github.io
      jbcom/nodejs-agentic-control
      jbcom/nodejs-agentic-triage
      jbcom/nodejs-otterfall
      jbcom/nodejs-pixels-pygame-palace
      jbcom/nodejs-rivermarsh
      jbcom/go-secretsync
      jbcom/rust-cosmic-cults
      jbcom/rust-agentic-game-generator
      strata-game-library/core
      strata-game-library/examples
      strata-game-library/shaders
      strata-game-library/presets
      strata-game-library/typescript-tutor
      strata-game-library/capacitor-plugin
      strata-game-library/react-native-plugin
      agentic-dev-library/control
      agentic-dev-library/triage
      agentic-dev-library/crew
      agentic-dev-library/game-generator
      extended-data-library/vendor-connectors
      extended-data-library/inputs
      extended-data-library/logging
      extended-data-library/core
      arcade-cabinet/rivers-of-reckoning

  # ============================================================================
  # Documentation scaffold - only for repos that need docs
  # These are more complex and should only be created if the docs/ dir is empty
  # ============================================================================
  - files:
      - source: repository-files/initial-only/docs/
        dest: docs/
        replace: false
    repos: |
      jbcom/python-agentic-crew
      jbcom/python-agentic-game-development
      jbcom/python-directed-inputs-class
      jbcom/python-extended-data-types
      jbcom/python-lifecyclelogging
      jbcom/python-vendor-connectors
      jbcom/nodejs-agentic-control
      jbcom/nodejs-agentic-triage
      jbcom/nodejs-otterfall
      jbcom/nodejs-pixels-pygame-palace
      jbcom/nodejs-rivermarsh
      jbcom/go-secretsync
      jbcom/rust-cosmic-cults
      jbcom/rust-agentic-game-generator
      strata-game-library/core
      strata-game-library/examples
      strata-game-library/shaders
      strata-game-library/presets
      strata-game-library/typescript-tutor
      strata-game-library/capacitor-plugin
      strata-game-library/react-native-plugin
      agentic-dev-library/control
      agentic-dev-library/triage
      agentic-dev-library/crew
      agentic-dev-library/game-generator
