# Centralized file sync configuration
# Syncs repository files from this control center to all jbcom repos
#
# Source: jbcom/jbcom-control-center (this repo)
# Action: BetaHuhn/repo-file-sync-action
#
# DIRECTORY STRUCTURE:
# ====================
# repository-files/
# ├── always-sync/     # Files that ALWAYS overwrite (rules must stay consistent)
# │   └── .cursor/rules/
# ├── initial-only/    # Files synced ONCE (repos can customize after)
# │   ├── .cursor/     # Dockerfile, environment.json
# │   ├── .github/     # Workflow files
# │   └── docs/        # Documentation scaffold
# ├── python/          # Python language rules
# ├── nodejs/          # Node.js/TypeScript language rules
# └── go/              # Go language rules
#
# SYNC BEHAVIOR:
# ==============
# - always-sync/: Overwrites on every sync (rules stay authoritative)
# - initial-only/: Only syncs if file doesn't exist (replace: false)
# - Language dirs: Always sync (language rules are authoritative)

# ============================================
# PYTHON PACKAGES
# ============================================

jbcom/extended-data-types:
  - source: repository-files/always-sync/
    dest: .
  - source: repository-files/python/
    dest: .
  - source: repository-files/initial-only/
    dest: .
    replace: false

jbcom/lifecyclelogging:
  - source: repository-files/always-sync/
    dest: .
  - source: repository-files/python/
    dest: .
  - source: repository-files/initial-only/
    dest: .
    replace: false

jbcom/directed-inputs-class:
  - source: repository-files/always-sync/
    dest: .
  - source: repository-files/python/
    dest: .
  - source: repository-files/initial-only/
    dest: .
    replace: false

jbcom/python-terraform-bridge:
  - source: repository-files/always-sync/
    dest: .
  - source: repository-files/python/
    dest: .
  - source: repository-files/initial-only/
    dest: .
    replace: false

jbcom/vendor-connectors:
  - source: repository-files/always-sync/
    dest: .
  - source: repository-files/python/
    dest: .
  - source: repository-files/initial-only/
    dest: .
    replace: false

# ============================================
# NODE.JS / TYPESCRIPT PACKAGES
# ============================================

jbcom/agentic-control:
  - source: repository-files/always-sync/
    dest: .
  - source: repository-files/nodejs/
    dest: .
  - source: repository-files/initial-only/
    dest: .
    replace: false

# ============================================
# GO PACKAGES
# ============================================

jbcom/vault-secret-sync:
  - source: repository-files/always-sync/
    dest: .
  - source: repository-files/go/
    dest: .
  - source: repository-files/initial-only/
    dest: .
    replace: false
