# Always-Sync Configuration
# These files are synced on EVERY run and OVERWRITE existing files
#
# Documentation: https://github.com/BetaHuhn/repo-file-sync-action

group:
  # ============================================================================
  # Core files - synced to ALL repositories
  # ============================================================================
  - files:
      # Cursor rules (always overwrite)
      - source: repository-files/always-sync/.cursor/
        dest: .cursor/
        deleteOrphaned: true
        exclude: |
          .gitkeep
      # GitHub config files (syncs all root-level .github files like CODEOWNERS, settings.yml, etc.)
      - source: repository-files/always-sync/.github/
        dest: .github/
        deleteOrphaned: false
    repos: &all_repos |
      jbcom/python-agentic-crew
      jbcom/python-agentic-game-development
      jbcom/python-directed-inputs-class
      jbcom/python-extended-data-types
      jbcom/python-lifecyclelogging
      jbcom/python-vendor-connectors
      jbcom/jbcom.github.io
      jbcom/nodejs-agentic-control
      jbcom/nodejs-agentic-triage
      jbcom/nodejs-otterfall
      jbcom/nodejs-pixels-pygame-palace
      jbcom/nodejs-rivermarsh
      jbcom/nodejs-strata
      jbcom/nodejs-strata-capacitor-plugin
      jbcom/nodejs-strata-examples
      jbcom/nodejs-strata-presets
      jbcom/nodejs-strata-react-native-plugin
      jbcom/nodejs-strata-shaders
      jbcom/nodejs-strata-typescript-tutor
      jbcom/go-secretsync
      jbcom/rust-cosmic-cults
      jbcom/rust-agentic-game-generator
      strata-game-library/core
      strata-game-library/examples
      strata-game-library/shaders
      strata-game-library/presets
      strata-game-library/typescript-tutor
      strata-game-library/capacitor-plugin
      strata-game-library/react-native-plugin
      agentic-dev-library/control
      agentic-dev-library/triage
      agentic-dev-library/crew
      agentic-dev-library/game-generator
      extended-data-library/vendor-connectors
      extended-data-library/inputs
      extended-data-library/logging
      extended-data-library/core
      arcade-cabinet/rivers-of-reckoning

  # ============================================================================
  # Python ecosystem - language-specific rules
  # ============================================================================
  - files:
      - source: repository-files/python/.cursor/
        dest: .cursor/
        deleteOrphaned: false
      - source: repository-files/python/.github/
        dest: .github/
        deleteOrphaned: false
    repos: &python_repos |
      jbcom/python-agentic-crew
      jbcom/python-agentic-game-development
      jbcom/python-directed-inputs-class
      jbcom/python-extended-data-types
      jbcom/python-lifecyclelogging
      jbcom/python-vendor-connectors
      extended-data-library/vendor-connectors
      extended-data-library/inputs
      extended-data-library/logging
      extended-data-library/core
      arcade-cabinet/rivers-of-reckoning

  # ============================================================================
  # Node.js ecosystem - language-specific rules
  # ============================================================================
  - files:
      - source: repository-files/nodejs/.cursor/
        dest: .cursor/
        deleteOrphaned: false
      - source: repository-files/nodejs/.github/
        dest: .github/
        deleteOrphaned: false
    repos: &nodejs_repos |
      jbcom/jbcom.github.io
      jbcom/nodejs-agentic-control
      jbcom/nodejs-agentic-triage
      jbcom/nodejs-otterfall
      jbcom/nodejs-pixels-pygame-palace
      jbcom/nodejs-rivermarsh
      jbcom/nodejs-strata
      jbcom/nodejs-strata-capacitor-plugin
      jbcom/nodejs-strata-examples
      jbcom/nodejs-strata-presets
      jbcom/nodejs-strata-react-native-plugin
      jbcom/nodejs-strata-shaders
      jbcom/nodejs-strata-typescript-tutor
      strata-game-library/core
      strata-game-library/examples
      strata-game-library/shaders
      strata-game-library/presets
      strata-game-library/typescript-tutor
      strata-game-library/capacitor-plugin
      strata-game-library/react-native-plugin
      agentic-dev-library/control
      agentic-dev-library/triage
      agentic-dev-library/crew
      agentic-dev-library/game-generator

  # ============================================================================
  # Go ecosystem - language-specific rules
  # ============================================================================
  - files:
      - source: repository-files/go/.cursor/
        dest: .cursor/
        deleteOrphaned: false
      - source: repository-files/go/.github/
        dest: .github/
        deleteOrphaned: false
    repos: &go_repos |
      jbcom/go-secretsync

  # ============================================================================
  # Rust ecosystem - language-specific rules
  # ============================================================================
  - files:
      - source: repository-files/rust/.cursor/
        dest: .cursor/
        deleteOrphaned: false
      - source: repository-files/rust/.github/
        dest: .github/
        deleteOrphaned: false
    repos: &rust_repos |
      jbcom/rust-cosmic-cults
      jbcom/rust-agentic-game-generator
