---
name: "Control Center - AI Reviewer"
author: "jbcom"
description: "AI-powered code review using Ollama GLM 4.6"

branding:
  icon: "eye"
  color: "blue"

runs:
  using: "docker"
  image: "docker://ghcr.io/jbcom/control-center:latest"
  args: ["reviewer"]
  env:
    CONTROL_CENTER_REPO: ${{ inputs.repo }}
    CONTROL_CENTER_PR: ${{ inputs.pr }}
    CONTROL_CENTER_LOG_LEVEL: ${{ inputs.log_level }}
    CONTROL_CENTER_DRY_RUN: ${{ inputs.dry_run }}

inputs:
  repo:
    description: "Repository (owner/name)"
    required: true
  pr:
    description: "Pull request number"
    required: true
  log_level:
    description: "Log level: debug, info, warn, error"
    required: false
    default: "info"
  dry_run:
    description: "Run without posting comments"
    required: false
    default: "false"

outputs:
  issues_found:
    description: "Number of issues found"
  approved:
    description: "Whether the PR was approved"
