# golangci-lint v2 configuration
# See https://golangci-lint.run/usage/configuration/
version: "2"

linters:
  # Enable specific linters (not formatters - gofmt/goimports are formatters in v2)
  enable:
    - govet         # Vet examines Go source code
    - ineffassign   # Detects unused assignments
    - staticcheck   # Includes gosimple
    - unused        # Checks for unused code
    - misspell      # Find commonly misspelled words
  # Disable problematic linters
  disable:
    - errcheck      # Too noisy with defer patterns

  # Linter-specific settings
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment  # Too noisy for this codebase
    staticcheck:
      checks:
        - all
        - -ST1005  # Allow capitalized error strings (API errors)

run:
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
