# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detects unused assignments
    - staticcheck   # Includes gosimple in v2
    - unused        # Checks for unused code
    - misspell      # Find commonly misspelled words
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment  # Too noisy for this codebase
    errcheck:
      exclude-functions:
        - io.Closer.Close
        - io.ReadCloser.Close
        - (*os.File).Close
        - (net/http.ResponseWriter).Write
        - os.Setenv
        - os.Unsetenv
        - os.Remove
        - (*github.com/spf13/cobra.Command).MarkFlagRequired
        - (*github.com/spf13/viper.Viper).BindPFlag
        - github.com/spf13/viper.BindPFlag
  exclusions:
    presets:
      - std-error-handling
      - common-false-positives
    rules:
      - path: ".*_test\\.go"
        linters:
          - errcheck
      - path: "tests/.*"
        linters:
          - errcheck

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true

run:
  timeout: 5m

output:
  formats:
    text:
      path: stdout
      print-issued-lines: true
      print-linter-name: true
      colors: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
