# golangci-lint v2 configuration
# See https://golangci-lint.run/usage/configuration/
version: "2"

linters:
  # Enable specific linters
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detects unused assignments
    - staticcheck   # Includes gosimple
    - unused        # Checks for unused code
    - misspell      # Find commonly misspelled words
    - gofmt         # Check formatting
    - goimports     # Check imports
  
  # Linter-specific settings
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment  # Too noisy for this codebase
    errcheck:
      exclude-functions:
        - io.Closer.Close
        - io.ReadCloser.Close
        - (*os.File).Close
        - (net/http.ResponseWriter).Write
        - os.Setenv
        - os.Unsetenv
        - os.Remove
        - (*github.com/spf13/cobra.Command).MarkFlagRequired
        - (*github.com/spf13/viper.Viper).BindPFlag
        - github.com/spf13/viper.BindPFlag
  
  # Exclusions
  exclusions:
    # Exclude test files from errcheck
    rules:
      - path: ".*_test\\.go"
        linters:
          - errcheck
      - path: "tests/.*"
        linters:
          - errcheck

run:
  timeout: 5m

output:
  # Maximum issues count per one linter
  max-issues-per-linter: 0
  # Maximum count of issues with the same text
  max-same-issues: 0
