# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: control-center

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: control-center
    main: ./cmd/control-center
    binary: control-center
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/jbcom/control-center/cmd/control-center/cmd.Version={{.Version}}
      - -X github.com/jbcom/control-center/cmd/control-center/cmd.Commit={{.Commit}}
      - -X github.com/jbcom/control-center/cmd/control-center/cmd.Date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch
  groups:
    - title: "🚀 Features"
      regexp: '^.*?feat(\([[:word:]]+\))?!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))?!?:.+$'
      order: 1
    - title: "⚡ Performance"
      regexp: '^.*?perf(\([[:word:]]+\))?!?:.+$'
      order: 2
    - title: "♻️ Refactoring"
      regexp: '^.*?refactor(\([[:word:]]+\))?!?:.+$'
      order: 3
    - title: "📦 Dependencies"
      regexp: '^.*?(deps|build)(\([[:word:]]+\))?!?:.+$'
      order: 4
    - title: "🔒 Security"
      regexp: '^.*?security(\([[:word:]]+\))?!?:.+$'
      order: 5
    - title: Others
      order: 999

release:
  github:
    owner: jbcom
    name: control-center
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## control-center {{ .Tag }}

    Enterprise AI orchestration for the jbcom ecosystem.

    ### Installation

    **Go:**
    ```bash
    go install github.com/jbcom/control-center/cmd/control-center@{{ .Version }}
    ```

    **Docker:**
    ```bash
    docker pull ghcr.io/jbcom/control-center:{{ .Version }}
    ```

    **Binary:**
    Download from the assets below for your platform.

    **GitHub Action:**
    ```yaml
    - uses: jbcom/control-center@{{ .Version }}
      with:
        command: reviewer
        repo: ${{ github.repository }}
        pr: ${{ github.event.pull_request.number }}
    ```

  footer: |
    ---
    **Full Changelog**: https://github.com/jbcom/control-center/compare/{{ .PreviousTag }}...{{ .Tag }}

# Docker images built separately
dockers: []
