---
name: "Control Center"
author: "jbcom"
description: "Enterprise AI orchestration - Gardener, Curator, Reviewer, Fixer for managing AI agents across repositories"

branding:
  icon: "cpu"
  color: "purple"

# Docker-based action using GHCR
runs:
  using: "docker"
  image: "docker://ghcr.io/jbcom/control-center:latest" # x-release-please-version
  args:
    - ${{ inputs.command }}
  env:
    CONTROL_CENTER_REPO: ${{ inputs.repo }}
    CONTROL_CENTER_PR: ${{ inputs.pr }}
    CONTROL_CENTER_RUN_ID: ${{ inputs.run_id }}
    CONTROL_CENTER_TARGET: ${{ inputs.target }}
    CONTROL_CENTER_DRY_RUN: ${{ inputs.dry_run }}
    CONTROL_CENTER_LOG_LEVEL: ${{ inputs.log_level }}
    CONTROL_CENTER_DECOMPOSE: ${{ inputs.decompose }}
    CONTROL_CENTER_BACKLOG: ${{ inputs.backlog }}

inputs:
  command:
    description: |
      Command to run:
        - gardener: Enterprise cascade orchestration
        - curator: Nightly issue/PR triage
        - reviewer: AI code review
        - fixer: CI failure analysis
    required: true

  repo:
    description: "Target repository (owner/name). Required for: curator, reviewer, fixer"
    required: false

  pr:
    description: "Pull request number. Required for: reviewer. Optional for: fixer"
    required: false

  run_id:
    description: "Workflow run ID. Alternative to --pr for: fixer"
    required: false

  target:
    description: |
      Target scope for gardener command:
        - all: All organizations
        - org-name: Specific organization
        - org-name/repo-name: Specific repository
    required: false
    default: "all"

  decompose:
    description: "For gardener: Cascade instructions to repository level"
    required: false
    default: "false"

  backlog:
    description: "For gardener: Process stale PRs and issues"
    required: false
    default: "true"

  dry_run:
    description: "Run without making changes (preview mode)"
    required: false
    default: "false"

  log_level:
    description: "Log verbosity: debug, info, warn, error"
    required: false
    default: "info"

  # API Keys (passed via environment, not as args for security)
  # Users should set these as secrets:
  #   GITHUB_TOKEN - Automatic in Actions
  #   OLLAMA_API_KEY - For reviewer/fixer
  #   GOOGLE_JULES_API_KEY - For curator delegation
  #   CURSOR_API_KEY - For curator delegation

outputs:
  result:
    description: "Command result (JSON)"
  issues_processed:
    description: "Number of issues processed (curator)"
  prs_reviewed:
    description: "Number of PRs reviewed (reviewer)"
  orgs_healed:
    description: "Number of orgs healed (gardener)"
