name: 'Agentic Issue Triage'
description: 'Triage a GitHub issue using an AI agent.'
author: 'jbcom/agentic-control'
branding:
  icon: 'alert-circle'
  color: 'orange'

inputs:
  github_token:
    description: 'The GitHub token to use for authentication.'
    required: true
  issue_number:
    description: 'The number of the issue to triage.'
    required: true
  model:
    description: 'The Ollama model to use for the triage.'
    required: false
    default: 'llama3'
  api_key:
    description: 'The API key for the model.'
    required: false
  cursor_api_key:
    description: 'Cursor API key'
    required: false
  comment_body:
    description: 'Comment body'
    required: false
  repository:
    description: 'Repository'
    required: false
  default_branch:
    description: 'Default branch'
    required: false

outputs:
  triage_summary:
    description: 'A summary of the triage.'
  labels:
    description: 'The labels suggested by the agent.'
  assignee:
    description: 'The assignee suggested by the agent.'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Run issue triage
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        CURSOR_API_KEY: ${{ inputs.cursor_api_key }}
        COMMENT_BODY: ${{ inputs.comment_body }}
        ISSUE_NUMBER: ${{ inputs.issue_number }}
        REPOSITORY: ${{ inputs.repository }}
        DEFAULT_BRANCH: ${{ inputs.default_branch }}
      run: |

        # If /cursor command is present, delegate to Cursor
        if [[ "$COMMENT_BODY" == *"/cursor"* ]]; then
          echo "🤖 Received '/cursor' command. Delegating to Cursor Cloud Agent..."
          # ... logic for Cursor delegation if needed ...
          gh issue comment "$ISSUE_NUMBER" --body "🤖 Received '/cursor' command. Cursor delegation is handled by the orchestrator."
          exit 0
        fi

        # Fallback to standard triage if no specific command
        echo "Performing standard issue triage..."
        # agentic-control@1.1.0 doesn't have issue-triage command yet
        # For now, we'll just acknowledge the issue
        # agentic triage quick "$COMMENT_BODY"
        gh issue comment "$ISSUE_NUMBER" --body "🤖 Issue received and queued for triage."
