name: 'Agentic PR Review'
description: 'AI-powered code review and feedback for Pull Requests'
author: 'Jon Bogaty'
branding:
  icon: 'search'
  color: 'blue'

inputs:
  github_token:
    description: 'GitHub token for API access'
    required: true
  model:
    description: 'AI model to use for review'
    required: false
  base:
    description: 'Base ref for diff'
    required: false
    default: 'main'
  head:
    description: 'Head ref for diff'
    required: false
    default: 'HEAD'
  ollama_api_key:
    description: 'Ollama API key (deprecated, use GH_TOKEN)'
    required: false
  ollama_host:
    description: 'Ollama host (deprecated)'
    required: false
  ollama_model:
    description: 'Ollama model (deprecated, use model)'
    required: false
  jules_api_key:
    description: 'Google Jules API key'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Run PR Review
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_MODEL: ${{ inputs.model }}
        INPUT_BASE: ${{ inputs.base }}
        INPUT_HEAD: ${{ inputs.head }}
        OLLAMA_API_KEY: ${{ inputs.ollama_api_key }}
        OLLAMA_HOST: ${{ inputs.ollama_host }}
        JULES_API_KEY: ${{ inputs.jules_api_key }}
      run: |
        declare -a ARGS
        if [ -n "$INPUT_MODEL" ]; then
          ARGS+=("--model" "$INPUT_MODEL")
        fi
        if [ -n "$INPUT_BASE" ]; then
          ARGS+=("--base" "$INPUT_BASE")
        fi
        if [ -n "$INPUT_HEAD" ]; then
          ARGS+=("--head" "$INPUT_HEAD")
        fi
        
        # Install peer dependencies first
        npm install -g agentic-control@1.1.0 @ai-sdk/anthropic @ai-sdk/google ai-sdk-ollama @ai-sdk/openai
        
        # Fetch base branch to ensure git diff works
        git fetch origin "${INPUT_BASE:-main}"
        git branch "${INPUT_BASE:-main}" FETCH_HEAD || true
        
        # Determine provider and configure
        if [ -n "$JULES_API_KEY" ]; then
          echo '{"triage": {"provider": "google"}}' > agentic.config.json
          export GOOGLE_API_KEY="$JULES_API_KEY"
          export GOOGLE_GENERATIVE_AI_API_KEY="$JULES_API_KEY"
          echo "Using Google provider with Jules key"
          # Force a known good Gemini model if using Google provider
          ARGS=("--model" "gemini-1.5-pro")
        elif [ -n "$OLLAMA_HOST" ]; then
          echo '{"triage": {"provider": "openai"}}' > agentic.config.json
          export OPENAI_API_KEY="${OLLAMA_API_KEY:-sk-no-key-required}"
          # Normalize URL: remove /v1 if present, then ensure exactly one /v1 at the end
          CLEAN_HOST="${OLLAMA_HOST%/}"
          CLEAN_HOST="${CLEAN_HOST%/v1}"
          export OPENAI_BASE_URL="${CLEAN_HOST}/v1"
          echo "Using Ollama via OpenAI shim at ${OPENAI_BASE_URL}"
        fi
        
        agentic triage review "${ARGS[@]}"
