name: 'Agentic Issue Triage'
description: 'Triage a GitHub issue using an AI agent.'
author: 'jbcom/agentic-control'
branding:
  icon: 'alert-circle'
  color: 'orange'

inputs:
  github_token:
    description: 'The GitHub token to use for authentication.'
    required: true
  issue_number:
    description: 'The number of the issue to triage.'
    required: true
  comment_body:
    description: 'Comment body'
    required: false
  repository:
    description: 'Repository'
    required: false
  default_branch:
    description: 'Default branch'
    required: false
  jules_api_key:
    description: 'Jules API key'
    required: false
  cursor_api_key:
    description: 'Cursor API key'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Run issue triage
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        JULES_API_KEY: ${{ inputs.jules_api_key }}
        GOOGLE_JULES_API_KEY: ${{ inputs.jules_api_key }}
        CURSOR_API_KEY: ${{ inputs.cursor_api_key }}
        COMMENT_BODY: ${{ inputs.comment_body }}
        ISSUE_NUMBER: ${{ inputs.issue_number }}
        REPOSITORY: ${{ inputs.repository }}
        DEFAULT_BRANCH: ${{ inputs.default_branch }}
        SENDER_TYPE: ${{ github.event.sender.type }}
      run: |
        set -euo pipefail

        # ======================================================================
        # Helper Functions
        # ======================================================================
        log() {
          echo "[$1] $2"
        }

        fail() {
          log "ERROR" "$1"
          gh issue comment "$ISSUE_NUMBER" --body "❌ **Error:** $1"
          exit 1
        }

        post_comment() {
          gh issue comment "$ISSUE_NUMBER" --body "$1"
        }

        # ======================================================================
        # Pre-flight Checks
        # ======================================================================
        if [[ "$SENDER_TYPE" == "Bot" ]]; then
          log "INFO" "Sender is a bot, ignoring."
          exit 0
        fi

        COMMAND=$(echo "$COMMENT_BODY" | xargs | awk '{print $1}')
        TASK=$(echo "$COMMENT_BODY" | sed -e "s|^$COMMAND[[:space:]]*||" | xargs | head -c 1000)

        # ======================================================================
        # /jules command
        # ======================================================================
        if [[ "$COMMAND" == "/jules" ]]; then
          log "INFO" "Received '/jules' command. Delegating to Google Jules..."
          
          if [[ -z "$GOOGLE_JULES_API_KEY" ]]; then
            fail "GOOGLE_JULES_API_KEY not configured. Cannot delegate to Jules."
          fi

          if [[ -z "$TASK" ]]; then
            read -r -d '' USAGE_MESSAGE << EOM
        ⚠️ **Missing task for '/jules' command.**

        To create a session, please provide a task description after the command.

        **Example:**
        \`/jules implement a new feature to do X\`
        EOM
            post_comment "$USAGE_MESSAGE"
            exit 0
          fi

          post_comment "🤖 Received task: \`$TASK\`. Creating Jules session..."

          JSON_PAYLOAD=$(jq -n \
            --arg task "Fix issue #$ISSUE_NUMBER: $TASK" \
            --arg repo "$REPOSITORY" \
            --arg branch "$DEFAULT_BRANCH" \
            '{
              prompt: $task,
              sourceContext: {
                source: ("sources/github/" + ($repo | split("/")[0]) + "/" + ($repo | split("/")[1])),
                githubRepoContext: { startingBranch: $branch }
              },
              automationMode: "AUTO_CREATE_PR"
            }')

          log "DEBUG" "Jules API Payload: $JSON_PAYLOAD"

          RESPONSE=$(curl -s -X POST "https://jules.googleapis.com/v1alpha/sessions" \
            -H "X-Goog-Api-Key: $GOOGLE_JULES_API_KEY" \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD")

          SESSION_URL=$(echo "$RESPONSE" | jq -r '.url // empty')

          if [[ -n "$SESSION_URL" ]]; then
            read -r -d '' SUCCESS_MESSAGE << EOM
        ## 🤖 Jules Session Created

        ➡️ **[Monitor Session]($SESSION_URL)**

        Jules will analyze the issue and create a PR.
        EOM
            post_comment "$SUCCESS_MESSAGE"
          else
            log "ERROR" "Failed to create Jules session: $RESPONSE"
            fail "Failed to create Jules session. Please check logs for details."
          fi
          exit 0
        fi

        # ======================================================================
        # /cursor command
        # ======================================================================
        if [[ "$COMMAND" == "/cursor" ]]; then
          log "INFO" "Received '/cursor' command. Delegation is handled by the orchestrator."
          post_comment "🤖 Received '/cursor' command. Cursor delegation is handled by the orchestrator."
          exit 0
        fi

        # ======================================================================
        # Fallback for other comments
        # ======================================================================
        log "INFO" "No command found. Exiting gracefully."
        exit 0
