name: 'Agentic Issue Triage'
description: 'Triage a GitHub issue using an AI agent.'
author: 'jbcom/agentic-control'
branding:
  icon: 'alert-circle'
  color: 'orange'

inputs:
  github_token:
    description: 'The GitHub token to use for authentication.'
    required: true
  issue_number:
    description: 'The number of the issue to triage.'
    required: true
  model:
    description: 'The Ollama model to use for the triage.'
    required: false
    default: 'llama3'
  api_key:
    description: 'The API key for the model.'
    required: false
  google_jules_api_key:
    description: 'Google Jules API key'
    required: false
  cursor_api_key:
    description: 'Cursor API key'
    required: false
  comment_body:
    description: 'Comment body'
    required: false
  repository:
    description: 'Repository'
    required: false
  default_branch:
    description: 'Default branch'
    required: false

outputs:
  triage_summary:
    description: 'A summary of the triage.'
  labels:
    description: 'The labels suggested by the agent.'
  assignee:
    description: 'The assignee suggested by the agent.'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Run issue triage
      uses: actions/github-script@v7
      with:
        script: |
          const {
            COMMENT_BODY,
            ISSUE_NUMBER,
            REPOSITORY,
            DEFAULT_BRANCH,
            GOOGLE_JULES_API_KEY
          } = process.env;

          // 1. Validate environment variables
          if (!COMMENT_BODY || !ISSUE_NUMBER || !REPOSITORY || !DEFAULT_BRANCH) {
            core.setFailed("Missing one or more required environment variables: COMMENT_BODY, ISSUE_NUMBER, REPOSITORY, DEFAULT_BRANCH");
            return;
          }

          // 2. Use regex for stricter command parsing
          const julesMatch = COMMENT_BODY.match(/^\/jules(\s+.*)?$/);
          const cursorMatch = COMMENT_BODY.match(/^\/cursor(\s+.*)?$/);

          if (julesMatch) {
            console.log("🤖 Received '/jules' command. Delegating to Google Jules...");

            if (!GOOGLE_JULES_API_KEY) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: ISSUE_NUMBER,
                body: "⚠️ GOOGLE_JULES_API_KEY not configured. Cannot delegate to Jules."
              });
              core.setFailed("GOOGLE_JULES_API_KEY not configured.");
              return;
            }

            const task = (julesMatch[1] || '').trim().substring(0, 1000);

            if (!task) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: ISSUE_NUMBER,
                body: "🤖 Received empty '/jules' command. Please provide a task.\n\n**Usage:** `/jules Implement the new login flow.`"
              });
              return;
            }

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ISSUE_NUMBER,
              body: `🤖 Received '/jules' command: \`${task}\`. Creating Jules session...`
            });

            // 3. Wrap fetch in try-catch
            try {
              const [owner, repo] = REPOSITORY.split('/');
              const response = await fetch("https://jules.googleapis.com/v1alpha/sessions", {
                method: "POST",
                headers: {
                  "X-Goog-Api-Key": GOOGLE_JULES_API_KEY,
                  "Content-Type": "application/json"
                },
                body: JSON.stringify({
                  prompt: `Fix issue #${ISSUE_NUMBER}: ${task}`,
                  sourceContext: {
                    source: `sources/github/${owner}/${repo}`,
                    githubRepoContext: {
                      startingBranch: DEFAULT_BRANCH
                    }
                  },
                  automationMode: "AUTO_CREATE_PR"
                })
              });

              const data = await response.json();
              const sessionId = data.id;
              const sessionUrl = data.url || `https://jules.google.com/session/${sessionId}`;

              if (sessionId) {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: ISSUE_NUMBER,
                  body: `## 🤖 Jules Session Created\n\n➡️ **[Monitor Session](${sessionUrl})**\n\nJules will analyze the issue and create a PR.`
                });
              } else {
                // 4. Remove raw API response from logs
                console.error("Failed to create Jules session. The API response did not contain a session ID.");
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: ISSUE_NUMBER,
                  body: "❌ Failed to create Jules session. The API response was invalid. Please check the action logs for details."
                });
                core.setFailed("Failed to create Jules session due to invalid API response.");
              }
            } catch (error) {
              console.error("An error occurred while creating the Jules session:", error);
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: ISSUE_NUMBER,
                body: "❌ An unexpected error occurred while creating the Jules session. Please check the action logs for details."
              });
              core.setFailed(`An unexpected error occurred: ${error.message}`);
            }

          } else if (cursorMatch) {
            console.log("🤖 Received '/cursor' command. Delegating to Cursor Cloud Agent...");
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ISSUE_NUMBER,
              body: "🤖 Received '/cursor' command. Cursor delegation is handled by the orchestrator."
            });
          } else {
            console.log("No command found. Performing standard issue triage...");
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ISSUE_NUMBER,
              body: "🤖 Issue received and queued for triage."
            });
          }
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GOOGLE_JULES_API_KEY: ${{ inputs.google_jules_api_key }}
        CURSOR_API_KEY: ${{ inputs.cursor_api_key }}
        COMMENT_BODY: ${{ inputs.comment_body }}
        ISSUE_NUMBER: ${{ inputs.issue_number }}
        REPOSITORY: ${{ inputs.repository }}
        DEFAULT_BRANCH: ${{ inputs.default_branch }}
