name: 'Agentic Issue Triage'
description: 'Triage a GitHub issue using an AI agent.'
author: 'jbcom/agentic-control'
branding:
  icon: 'alert-circle'
  color: 'orange'

inputs:
  github_token:
    description: 'The GitHub token to use for authentication.'
    required: true
  issue_number:
    description: 'The number of the issue to triage.'
    required: true
  model:
    description: 'The Ollama model to use for the triage.'
    required: false
    default: 'llama3'
  api_key:
    description: 'The API key for the model.'
    required: false
  jules_api_key:
    description: 'Jules API key'
    required: false
  cursor_api_key:
    description: 'Cursor API key'
    required: false
  comment_body:
    description: 'Comment body'
    required: false
  repository:
    description: 'Repository'
    required: false
  default_branch:
    description: 'Default branch'
    required: false

outputs:
  triage_summary:
    description: 'A summary of the triage.'
  labels:
    description: 'The labels suggested by the agent.'
  assignee:
    description: 'The assignee suggested by the agent.'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Run issue triage
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        JULES_API_KEY: ${{ inputs.jules_api_key }}
        GOOGLE_JULES_API_KEY: ${{ inputs.jules_api_key }}
        CURSOR_API_KEY: ${{ inputs.cursor_api_key }}
        COMMENT_BODY: ${{ inputs.comment_body }}
        ISSUE_NUMBER: ${{ inputs.issue_number }}
        REPOSITORY: ${{ inputs.repository }}
        DEFAULT_BRANCH: ${{ inputs.default_branch }}
      run: |
        set -euo pipefail

        # Trim leading/trailing whitespace
        COMMENT_TRIMMED=$(echo "${COMMENT_BODY}" | xargs)

        # --- Helper Functions ---
        post_error() {
          local message="$1"
          gh issue comment "$ISSUE_NUMBER" --repo "$REPOSITORY" --body "❌ **Error:** ${message}"
          exit 1
        }

        post_usage() {
          local command="$1"
          local example_prompt="$2"
          gh issue comment "$ISSUE_NUMBER" --repo "$REPOSITORY" --body "⚠️ **Invalid command.** Usage: \`/${command} ${example_prompt}\`"
          exit 0
        }

        # --- Command Routing ---
        if [[ "$COMMENT_TRIMMED" == /jules || "$COMMENT_TRIMMED" == /jules* ]]; then
          echo "🤖 Received '/jules' command. Delegating to Google Jules..."
          
          PROMPT=$(echo "$COMMENT_TRIMMED" | sed -E 's|^/jules[[:space:]]+||')
          if [[ "$PROMPT" == "/jules" || -z "$PROMPT" ]]; then
            post_usage "jules" "Fix this issue by implementing X"
          fi

          if [[ -z "$GOOGLE_JULES_API_KEY" ]]; then
            post_error "GOOGLE_JULES_API_KEY not configured for this repository."
          fi

          RESPONSE=$(curl -s -X POST "https://jules.googleapis.com/v1alpha/sessions" \
            -H "X-Goog-Api-Key: $GOOGLE_JULES_API_KEY" \
            -H "Content-Type: application/json" \
            -d "$(jq -n \
              --arg task "$PROMPT" \
              --arg repo "$REPOSITORY" \
              --arg branch "$DEFAULT_BRANCH" \
              --arg issue_num "$ISSUE_NUMBER" \
              '{
                prompt: $task,
                sourceContext: {
                  source: ("sources/github/" + ($repo | split("/")[0]) + "/" + ($repo | split("/")[1])),
                  githubRepoContext: { startingBranch: $branch }
                },
                automationMode: "AUTO_CREATE_PR",
                title: ("Jules: Address issue #" + $issue_num)
              }')")

          SESSION_ID=$(echo "$RESPONSE" | jq -r '.name // empty' | sed 's|sessions/||')
          SESSION_URL=$(echo "$RESPONSE" | jq -r '.url // empty')

          if [ -n "$SESSION_ID" ] && [ -n "$SESSION_URL" ]; then
            gh issue comment "$ISSUE_NUMBER" --repo "$REPOSITORY" --body "## 🤖 Jules Session Created\n\n➡️ **[Monitor Session](${SESSION_URL})**\n\nJules will analyze the issue and create a PR."
          else
            echo "Failed to create Jules session: $RESPONSE"
            post_error "Failed to create Jules session. Please check logs for details."
          fi
          exit 0
        fi

        if [[ "$COMMENT_TRIMMED" == /cursor || "$COMMENT_TRIMMED" == /cursor* ]]; then
          echo "🤖 Received '/cursor' command. Delegating to Cursor Cloud Agent..."

          PROMPT=$(echo "$COMMENT_TRIMMED" | sed -E 's|^/cursor[[:space:]]+||')
          if [[ "$PROMPT" == "/cursor" || -z "$PROMPT" ]]; then
            post_usage "cursor" "Implement the feature described in this issue"
          fi

          if [[ -z "$CURSOR_API_KEY" ]]; then
            post_error "CURSOR_API_KEY not configured for this repository."
          fi

          # NOTE: Orchestrator workflow handles the actual Cursor delegation.
          # This action only validates and provides user feedback.
          gh issue comment "$ISSUE_NUMBER" --repo "$REPOSITORY" --body "✅ **Cursor command acknowledged.** The Ecosystem Orchestrator will now spawn a Cursor agent."
          exit 0
        fi

        # Fallback to standard triage if no specific command
        echo "Performing standard issue triage..."
        # agentic-control@1.1.0 doesn't have issue-triage command yet
        # For now, we'll just acknowledge the issue
        # agentic triage quick "$COMMENT_BODY"
        gh issue comment "$ISSUE_NUMBER" --body "🤖 Issue received and queued for triage."
