name: 'Agentic Issue Triage'
description: 'Triage a GitHub issue using an AI agent.'
author: 'jbcom/agentic-control'
branding:
  icon: 'alert-circle'
  color: 'orange'

inputs:
  github_token:
    description: 'The GitHub token to use for authentication.'
    required: true
  issue_number:
    description: 'The number of the issue to triage.'
    required: true
  model:
    description: 'The Ollama model to use for the triage.'
    required: false
    default: 'llama3'
  api_key:
    description: 'The API key for the model.'
    required: false
  jules_api_key:
    description: 'Jules API key'
    required: false
  cursor_api_key:
    description: 'Cursor API key'
    required: false
  comment_body:
    description: 'Comment body'
    required: false
  repository:
    description: 'Repository'
    required: false
  default_branch:
    description: 'Default branch'
    required: false

outputs:
  triage_summary:
    description: 'A summary of the triage.'
  labels:
    description: 'The labels suggested by the agent.'
  assignee:
    description: 'The assignee suggested by the agent.'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Run issue triage
      uses: actions/github-script@v7
      with:
        script: |
          const { COMMENT_BODY, ISSUE_NUMBER, REPOSITORY, DEFAULT_BRANCH, GOOGLE_JULES_API_KEY } = process.env;

          if (COMMENT_BODY.includes('/jules')) {
            console.log("🤖 Received '/jules' command. Delegating to Google Jules...");

            if (!GOOGLE_JULES_API_KEY) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: ISSUE_NUMBER,
                body: "⚠️ GOOGLE_JULES_API_KEY not configured. Cannot delegate to Jules."
              });
              return;
            }

            const task = COMMENT_BODY.replace(/\/jules\s*/, '').trim().substring(0, 1000);

            if (!task) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: ISSUE_NUMBER,
                body: "🤖 Received empty '/jules' command. Please provide a task.\n\n**Usage:** `/jules Implement the new login flow.`"
              });
              return;
            }

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ISSUE_NUMBER,
              body: `🤖 Received '/jules' command: \`${task}\`. Creating Jules session...`
            });

            const [owner, repo] = REPOSITORY.split('/');
            const response = await fetch("https://jules.googleapis.com/v1alpha/sessions", {
              method: "POST",
              headers: {
                "X-Goog-Api-Key": GOOGLE_JULES_API_KEY,
                "Content-Type": "application/json"
              },
              body: JSON.stringify({
                prompt: `Fix issue #${ISSUE_NUMBER}: ${task}`,
                sourceContext: {
                  source: `sources/github/${owner}/${repo}`,
                  githubRepoContext: { startingBranch: DEFAULT_BRANCH }
                },
                automationMode: "AUTO_CREATE_PR"
              })
            });

            const data = await response.json();
            const sessionId = data.id;
            const sessionUrl = `https://jules.google.com/session/${sessionId}`;

            if (sessionId) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: ISSUE_NUMBER,
                body: `## 🤖 Jules Session Created\n\n➡️ **[Monitor Session](${sessionUrl})**\n\nJules will analyze the issue and create a PR.`
              });
            } else {
              console.error("Failed to create Jules session:", data);
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: ISSUE_NUMBER,
                body: "❌ Failed to create Jules session. Please check logs."
              });
              core.setFailed("Failed to create Jules session.");
            }
          } else if (COMMENT_BODY.includes('/cursor')) {
            console.log("🤖 Received '/cursor' command. Delegating to Cursor Cloud Agent...");
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ISSUE_NUMBER,
              body: "🤖 Received '/cursor' command. Cursor delegation is handled by the orchestrator."
            });
          } else {
            console.log("Performing standard issue triage...");
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ISSUE_NUMBER,
              body: "🤖 Issue received and queued for triage."
            });
          }
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        JULES_API_KEY: ${{ inputs.jules_api_key }}
        GOOGLE_JULES_API_KEY: ${{ inputs.jules_api_key }}
        CURSOR_API_KEY: ${{ inputs.cursor_api_key }}
        COMMENT_BODY: ${{ inputs.comment_body }}
        ISSUE_NUMBER: ${{ inputs.issue_number }}
        REPOSITORY: ${{ inputs.repository }}
        DEFAULT_BRANCH: ${{ inputs.default_branch }}
