name: 'Agentic Issue Triage'
description: 'Triage a GitHub issue using an AI agent.'
author: 'jbcom/agentic-control'
branding:
  icon: 'alert-circle'
  color: 'orange'

inputs:
  github_token:
    description: 'The GitHub token to use for authentication.'
    required: true
  issue_number:
    description: 'The number of the issue to triage.'
    required: true
  model:
    description: 'The Ollama model to use for the triage.'
    required: false
    default: 'llama3'
  api_key:
    description: 'The API key for the model.'
    required: false
  comment_body:
    description: 'Comment body'
    required: false

outputs:
  triage_summary:
    description: 'A summary of the triage.'
  labels:
    description: 'The labels suggested by the agent.'
  assignee:
    description: 'The assignee suggested by the agent.'

runs:
  using: 'composite'
  steps:
    - name: Run issue triage
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        ISSUE_NUMBER: ${{ inputs.issue_number }}
        COMMENT_BODY: ${{ inputs.comment_body }}
      run: |
        # Fallback to standard triage if no specific command
        echo "Performing standard issue triage..."
        gh issue comment "$ISSUE_NUMBER" --body "🤖 Issue received and queued for triage."
