name: "Release ${pipeline_name}"

concurrency:
  cancel-in-progress: true
  group: "${pipeline_name}-$${{github.ref}}"

on:
%{ if length(workflow.branches) > 0 || length(workflow.paths) > 0 ~}
  push:
%{ if length(workflow.branches) > 0 ~}
    branches:
%{ for branch in workflow.branches ~}
      - "${branch}"
%{ endfor ~}
%{ endif ~}
%{ if length(workflow.paths) > 0 ~}
    paths:
      - ".github/workflows/${pipeline_name}.yml"
%{ for path in workflow.paths ~}
      - "${path}"
%{ endfor ~}
%{ endif ~}
%{ else ~}
  push: {}
%{ endif ~}
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  build-and-push:
    name: Build and Push ${build.ecr_repository}
    runs-on: ubuntu-latest
    outputs:
      image-url: ${build.repository_url}@$${{steps.docker-build-and-push.outputs.digest}}
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: $${{secrets.EXTERNAL_CI_ACCESS_KEY}}
          aws-secret-access-key: $${{secrets.EXTERNAL_CI_SECRET_KEY}}
          aws-region: us-east-1
          role-to-assume: ${execution_role_arn}
          role-skip-session-tagging: true
          role-duration-seconds: 3600
          mask-aws-account-id: no
%{ if build.pre_build != "" ~}
      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1.4.1
      - name: Pre-build
        run: |
          $${{ build.pre_build }}
%{ endif ~}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - uses: docker/setup-buildx-action@v2
      - name: Build and push image
        id: docker-build-and-push
        uses: docker/build-push-action@v4
        with:
%{ for k, v in build.docker ~}
%{ if k != "tags" && v != null ~}
          ${k}: ${try(join(",", v), v)}
%{ endif ~}
%{ endfor ~}
          tags: ${join(",", concat(build.docker.tags, ["${build.repository_url}:latest","${build.repository_url}:$${{github.sha}}"]))}

%{ for task_name, task_config in deploy ~}
%{ if task_config.task_definition_family != "" ~}
  ${task_name}:
    name: Deploy ${task_name}
    needs: build-and-push
    defaults:
      run:
        shell: "bash"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: $${{secrets.EXTERNAL_CI_ACCESS_KEY}}
          aws-secret-access-key: $${{secrets.EXTERNAL_CI_SECRET_KEY}}
          aws-region: us-east-1
          role-to-assume: ${execution_role_arn}
          role-skip-session-tagging: true
          role-duration-seconds: 3600
          mask-aws-account-id: no
      - name: Pull task definition
        run: |
          aws ecs describe-task-definition \
          --task-definition '${task_config.task_definition_family}' \
          --query taskDefinition > task-definition.json
%{ for container_pos, container_definition_name in task_config.container_definitions ~}
      - name: Update the image for container ${container_definition_name}
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        id: update-container-${container_pos}
        with:
%{ if container_pos == 0 ~}
          task-definition: task-definition.json
%{ else ~}
          task-definition: $${{steps.update-container-${container_pos - 1}.outputs.task-definition}}
%{ endif ~}
          container-name: ${container_definition_name}
          image: $${{needs.build-and-push.outputs.image-url}}
%{ endfor ~}
%{ if task_config.service_name != "" ~}
      - name: Deploy to Amazon ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: $${{steps.update-container-${length(task_config.container_definitions) -1}.outputs.task-definition}}
          service: ${task_config.service_name}
          cluster: ${task_config.cluster_name}
%{ endif ~}
%{ endif ~}
%{ endfor ~}