AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  secrets-config - Preprocessor Lambda for secrets pipeline.
  
  Loads config from SSM, discovers accounts via Organizations and Identity Center,
  builds merging context, writes to S3, and triggers the merging Lambda.

Parameters:
  SecretsBucketName:
    Type: String
    Description: S3 bucket for storing context and secrets
  SecretsBucketArn:
    Type: String
    Description: ARN of the S3 bucket
  MergingFunctionName:
    Type: String
    Default: secrets-merging
    Description: Name of the merging Lambda to trigger
  ScheduleExpression:
    Type: String
    Default: rate(6 hours)
    Description: Backup schedule (in case SSM events are missed)

Globals:
  Function:
    Timeout: 300
    MemorySize: 512
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON

Resources:
  SecretsConfigFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: secrets-config
      Description: Preprocesses secrets config and triggers merging pipeline
      CodeUri: handler/
      Handler: handler.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Environment:
        Variables:
          # Minimal config - everything else discovered or from vendor secrets
          TM_VENDORS_SOURCE: asm
          SECRETS_BUCKET: !Ref SecretsBucketName
          MERGING_FUNCTION_NAME: !Ref MergingFunctionName
          # Convention-based defaults (can override via event)
          SSM_PREFIX: /terraform-modules/secrets-config
          RECORDS_KEY: records/workspaces/secrets/merging.json
      Events:
        SsmParameterChange:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.ssm
              detail-type:
                - Parameter Store Change
              detail:
                name:
                  - prefix: /terraform-modules/secrets-config
                operation:
                  - Create
                  - Update
        ScheduledRun:
          Type: Schedule
          Properties:
            Schedule: !Ref ScheduleExpression
            Description: Backup trigger for secrets config preprocessing
            Enabled: true
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Sid: SsmRead
              Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParameters
                - ssm:GetParametersByPath
              Resource:
                - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/terraform-modules/*"
            - Sid: S3Write
              Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
              Resource:
                - !Sub "${SecretsBucketArn}/*"
            - Sid: OrganizationsRead
              Effect: Allow
              Action:
                - organizations:ListAccounts
                - organizations:DescribeAccount
              Resource: "*"
            - Sid: IdentityStoreRead
              Effect: Allow
              Action:
                - sso:ListInstances
                - sso-admin:ListInstances
                - identitystore:ListGroups
                - identitystore:ListGroupMemberships
                - identitystore:DescribeUser
                - identitystore:DescribeGroup
              Resource: "*"
            - Sid: LambdaInvoke
              Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource:
                - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${MergingFunctionName}"
            - Sid: SecretsManagerRead
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:ListSecrets
              Resource: "*"

  SecretsConfigLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${SecretsConfigFunction}"
      RetentionInDays: 14

Outputs:
  SecretsConfigFunctionArn:
    Description: Secrets Config Lambda Function ARN
    Value: !GetAtt SecretsConfigFunction.Arn
