# Sync configuration for extended-data-types package
# Syncs from monorepo to public individual repo

group:
  - files:
      - source: packages/extended-data-types/
        dest: .
        exclude: |
          .git
          .github
          __pycache__
          *.pyc
          .pytest_cache
          .tox
          .venv
          dist
          build
          *.egg-info
    repos: |
      jbcom/extended-data-types
