# Sync configuration for python-terraform-bridge package
# Syncs from monorepo to public container repo

group:
  - files:
      - source: packages/python-terraform-bridge/
        dest: .
        exclude: |
          .git
          .github
          __pycache__
          *.pyc
          .pytest_cache
          .tox
          .venv
          dist
          build
          *.egg-info
    repos: |
      jbcom/python-terraform-bridge
