# Sync configuration for vault-secret-sync package
# Syncs from monorepo to public individual repo

group:
  - files:
      - source: packages/vault-secret-sync/
        dest: .
        exclude: |
          .git
          .github
          .gitignore
          .env-sample
          __pycache__
          *.pyc
          .DS_Store
          *.log
    repos: |
      jbcom/vault-secret-sync
