name: Template Validation

# This CI validates the TEMPLATE ITSELF, not the distributed workflow
# It ensures all scripts, workflows, and processes are correct

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  validate-python-scripts:
    name: Validate Python Scripts
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install validation dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy pytest yamllint
      
      - name: Lint Python scripts with ruff
        run: |
          ruff check .github/scripts/
          ruff format --check .github/scripts/
      
      - name: Type check scripts with mypy
        run: |
          mypy --strict .github/scripts/
      
      - name: Test set_version.py script
        env:
          GITHUB_RUN_NUMBER: 999
        run: |
          # Test the versioning script
          python .github/scripts/set_version.py
          
          # Verify it actually updated the version
          grep -q "__version__ = \"[0-9]\{4\}\.[0-9]\{1,2\}\.999\"" src/example_package/__init__.py
          
          echo "✅ Version script works correctly"

  validate-workflows:
    name: Validate GitHub Actions Workflows
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      
      - name: Validate workflow YAML syntax
        run: |
          sudo snap install yq
          
          for workflow in .github/workflows/*.yml; do
            echo "Validating $workflow"
            yq eval . "$workflow" > /dev/null || exit 1
          done
          
          echo "✅ All workflows have valid YAML syntax"
      
      - name: Check for required workflow components
        run: |
          # Ensure ci.yml exists for distribution
          if [ ! -f .github/workflows/ci.yml ]; then
            echo "❌ Missing .github/workflows/ci.yml"
            exit 1
          fi
          
          # Ensure template-validation.yml exists
          if [ ! -f .github/workflows/template-validation.yml ]; then
            echo "❌ Missing .github/workflows/template-validation.yml"
            exit 1
          fi
          
          echo "✅ Required workflow files present"

  validate-template-structure:
    name: Validate Template Structure
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      
      - name: Check required files
        run: |
          required_files=(
            "pyproject.toml"
            "README.md"
            "AGENTS.md"
            "TEMPLATE_USAGE.md"
            ".cursorrules"
            ".github/copilot-instructions.md"
            ".github/scripts/set_version.py"
            ".github/workflows/ci.yml"
            "src/example_package/__init__.py"
            "tests/test_default.py"
          )
          
          for file in "${required_files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing required file: $file"
              exit 1
            fi
          done
          
          echo "✅ All required template files present"
      
      - name: Verify placeholders are documented
        run: |
          # Check that documentation mentions ${REPO_NAME} placeholder
          if ! grep -q '\${REPO_NAME}' AGENTS.md; then
            echo "❌ AGENTS.md should document \${REPO_NAME} placeholder"
            exit 1
          fi
          
          echo "✅ Placeholders properly documented"
      
      - name: Check for leftover project-specific content
        run: |
          # copilot-instructions.md should use ${REPO_NAME} placeholder
          if grep -q "lifecyclelogging" .github/copilot-instructions.md; then
            echo "⚠️  Warning: copilot-instructions.md contains 'lifecyclelogging' - should use \${REPO_NAME}"
          fi
          
          # Check for extended-data-types in examples
          if grep -q "from extended_data_types import" .github/copilot-instructions.md; then
            echo "⚠️  Warning: copilot-instructions.md contains project-specific imports"
          fi

  validate-package-structure:
    name: Validate Example Package
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install package in development mode
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[tests,typing]"
      
      - name: Run example tests
        run: |
          pytest tests/ -v
      
      - name: Verify package can be imported
        run: |
          python -c "import example_package; print(f'Version: {example_package.__version__}')"

  lint-template-code:
    name: Lint Template Code Quality
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      
      - name: Run ruff linter
        run: |
          ruff check src/ tests/ --output-format=github
      
      - name: Run ruff formatter check
        run: |
          ruff format --check src/ tests/

  validate-documentation:
    name: Validate Documentation
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      
      - name: Check README completeness
        run: |
          required_sections=(
            "Quick Start"
            "Usage"
            "CalVer"
          )
          
          for section in "${required_sections[@]}"; do
            if ! grep -qi "$section" README.md; then
              echo "⚠️  Warning: README.md should contain '$section' section"
            fi
          done
      
      - name: Validate AGENTS.md structure
        run: |
          if ! grep -q "CalVer" AGENTS.md; then
            echo "❌ AGENTS.md must document CalVer approach"
            exit 1
          fi
          
          if ! grep -q "semantic-release" AGENTS.md; then
            echo "❌ AGENTS.md must explain why NOT to use semantic-release"
            exit 1
          fi
          
          echo "✅ AGENTS.md has required content"
      
      - name: Check for markdown lint issues
        run: |
          sudo npm install -g markdownlint-cli
          markdownlint *.md --ignore node_modules --ignore .github || echo "⚠️  Markdown lint warnings found"

  validate-ruler-structure:
    name: Validate Ruler Configuration
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      
      - name: Check ruler directory exists
        run: |
          if [ ! -d ".ruler" ]; then
            echo "⚠️  .ruler directory not found - may not be initialized yet"
            exit 0
          fi
          
          # If .ruler exists, validate its structure
          if [ ! -f ".ruler/config.yaml" ]; then
            echo "❌ Missing .ruler/config.yaml"
            exit 1
          fi
          
          echo "✅ Ruler structure validated"
