AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  secrets-merging - Lambda for merging secrets from multiple sources.
  
  Receives context from secrets-config via S3, fetches secrets from import sources,
  merges them, and writes results to S3 for the syncing lambda.

Parameters:
  SecretsBucketName:
    Type: String
    Description: S3 bucket for secrets storage (context and merged secrets)
  SecretsBucketArn:
    Type: String
    Description: ARN of the S3 bucket
  KmsKeyArn:
    Type: String
    Description: KMS key ARN for encrypting S3 objects
  ScheduleExpression:
    Type: String
    Default: rate(30 minutes)
    Description: EventBridge schedule for running the merge operation

Globals:
  Function:
    Timeout: 900
    MemorySize: 1024
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON

Resources:
  TerraformModulesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: terraform-modules-lib
      Description: terraform_modules Python library
      ContentUri: ../../
      CompatibleRuntimes:
        - python3.13
        - python3.12
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.13
      BuildArchitecture: x86_64

  SecretsMergingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: secrets-merging
      Description: Merges secrets from multiple AWS accounts and Vault sources
      CodeUri: handler/
      Handler: handler.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Layers:
        - !Ref TerraformModulesLayer
      Environment:
        Variables:
          # Operation mode - everything else comes from context or vendor secrets
          TM_OPERATION: merge_secrets
          TM_VENDORS_SOURCE: asm
          # S3 bucket is the only "infrastructure" config needed
          SECRETS_BUCKET: !Ref SecretsBucketName
      Events:
        ScheduledMerge:
          Type: Schedule
          Properties:
            Schedule: !Ref ScheduleExpression
            Description: Scheduled secrets merge operation
            Enabled: true
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Sid: S3Access
              Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:ListBucket
              Resource:
                - !Ref SecretsBucketArn
                - !Sub "${SecretsBucketArn}/*"
            - Sid: KmsAccess
              Effect: Allow
              Action:
                - kms:Decrypt
                - kms:Encrypt
                - kms:GenerateDataKey
              Resource:
                - !Ref KmsKeyArn
            - Sid: AssumeImportRoles
              Effect: Allow
              Action:
                - sts:AssumeRole
              Resource:
                - "arn:aws:iam::*:role/secrets-import-*"
                - "arn:aws:iam::*:role/AWSControlTowerExecution"
            - Sid: SecretsManagerAccess
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:ListSecrets
              Resource: "*"

  SecretsMergingLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${SecretsMergingFunction}"
      RetentionInDays: 30

Outputs:
  SecretsMergingFunctionArn:
    Description: Secrets Merging Lambda Function ARN
    Value: !GetAtt SecretsMergingFunction.Arn
  TerraformModulesLayerArn:
    Description: Terraform Modules Layer ARN
    Value: !Ref TerraformModulesLayer
    Export:
      Name: TerraformModulesLayerArn
