AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  secrets-syncing - Lambda for syncing merged secrets to target accounts.
  
  Triggered by S3 object creation when merging lambda writes secrets/{target}.json.
  Looks up execution role from context and syncs to target account's Secrets Manager.

Parameters:
  SecretsBucketName:
    Type: String
    Description: S3 bucket containing merged secrets
  SecretsBucketArn:
    Type: String
    Description: ARN of the S3 bucket
  KmsKeyArn:
    Type: String
    Description: KMS key ARN for decrypting S3 objects
  TerraformModulesLayerArn:
    Type: String
    Description: ARN of the shared terraform_modules layer
    Default: ''

Globals:
  Function:
    Timeout: 600
    MemorySize: 512
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON

Conditions:
  CreateLayer: !Equals [!Ref TerraformModulesLayerArn, '']

Resources:
  TerraformModulesLayer:
    Type: AWS::Serverless::LayerVersion
    Condition: CreateLayer
    Properties:
      LayerName: terraform-modules-lib-syncing
      Description: terraform_modules Python library
      ContentUri: ../../
      CompatibleRuntimes:
        - python3.13
        - python3.12
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.13
      BuildArchitecture: x86_64

  SecretsSyncingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: secrets-syncing
      Description: Syncs merged secrets to target AWS accounts
      CodeUri: handler/
      Handler: handler.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Layers:
        - !If 
          - CreateLayer
          - !Ref TerraformModulesLayer
          - !Ref TerraformModulesLayerArn
      Environment:
        Variables:
          # Operation mode - target and role come from S3 key + context lookup
          TM_OPERATION: sync_secrets
          TM_VENDORS_SOURCE: asm
          SECRETS_BUCKET: !Ref SecretsBucketName
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Sid: S3Access
              Effect: Allow
              Action:
                - s3:GetObject
                - s3:ListBucket
              Resource:
                - !Ref SecretsBucketArn
                - !Sub "${SecretsBucketArn}/*"
            - Sid: KmsDecrypt
              Effect: Allow
              Action:
                - kms:Decrypt
              Resource:
                - !Ref KmsKeyArn
            - Sid: AssumeTargetRoles
              Effect: Allow
              Action:
                - sts:AssumeRole
              Resource:
                - "arn:aws:iam::*:role/secrets-sync-*"
                - "arn:aws:iam::*:role/AWSControlTowerExecution"
                - "arn:aws:iam::*:role/OrganizationAccountAccessRole"
            - Sid: SecretsManagerAccess
              Effect: Allow
              Action:
                - secretsmanager:CreateSecret
                - secretsmanager:PutSecretValue
                - secretsmanager:GetSecretValue
                - secretsmanager:DeleteSecret
                - secretsmanager:RestoreSecret
                - secretsmanager:ListSecrets
              Resource: "*"

  S3InvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt SecretsSyncingFunction.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Ref SecretsBucketArn

  SecretsSyncingLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${SecretsSyncingFunction}"
      RetentionInDays: 30

Outputs:
  SecretsSyncingFunctionArn:
    Description: Secrets Syncing Lambda Function ARN
    Value: !GetAtt SecretsSyncingFunction.Arn
