concurrency:
  group: ${workflow_name}
  cancel-in-progress: true

name: ${workflow_name}

on:
%{ if sync_on_push ~}
  push:
%{ if length(push_triggers.branches) > 0 ~}
    branches:
%{ for branch in push_triggers.branches ~}
      - ${branch}
%{ endfor ~}
%{ endif ~}
%{ if length(push_triggers.paths) > 0 ~}
    paths:
%{ for path in push_triggers.paths ~}
      - '${path}'
%{ endfor ~}
%{ endif ~}
%{ endif ~}
%{ if sync_on_call ~}
  workflow_call: {}
%{ endif ~}
%{ if sync_on_dispatch ~}
  workflow_dispatch: {}
%{ endif ~}
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          token: $${{ secrets.FLIPSIDE_GITHUB_TOKEN }}
      - name: Run GitHub File Sync
        id: repo-file-sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: $${{ secrets.FLIPSIDE_GITHUB_TOKEN }}
          GIT_EMAIL: 'devops-flipsidecrypto@users.noreply.github.com'
          GIT_USERNAME: 'devops-flipsidecrypto'
          SKIP_PR: ${skip_pr}
          CONFIG_PATH: ${config_path}
          COMMIT_EACH_FILE: ${commit_each_file}
          COMMIT_PREFIX: '${commit_prefix}'
%{ if branch_prefix != null ~}
          BRANCH_PREFIX: ${branch_prefix}
%{ endif ~}
%{ if slack_notifications && !skip_pr ~}
      - name: Generate Slack message
        id: slack-message
        run: |
          set -exo pipefail
          
          SLACK_MESSAGE=$(echo $PULL_REQUESTS | sed -e 's/\[//g' -e 's/\]//g' -e 's/\,/ /g' -e 's/\"//g')
                    
          echo "title=New sync pull requests from $${GITHUB_REPOSITORY}" >> $GITHUB_OUTPUT
          echo "message=$${SLACK_MESSAGE}" >> $GITHUB_OUTPUT
        env:
         PULL_REQUESTS: $${{ steps.repo-file-sync.outputs.pull_request_urls }}
      - name: Notify Slack
        id: slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: $${{ secrets.${slack_webhook_url_secret_name} }}
          SLACK_USERNAME: 'devops-flipsidecrypto'
          SLACK_MSG_AUTHOR: 'devops-flipsidecrypto'
          SLACK_ICON_EMOJI: ':godmode:'
          MSG_MINIMAL: true
          SLACK_TITLE: $${{ steps.slack-message.outputs.title }}
          SLACK_MESSAGE: |
            $${{ steps.slack-message.outputs.message }}
          SLACK_FOOTER: 'Please review and merge'
  %{ endif ~}