AWSTemplateFormatVersion: 2010-09-09
Description: 'CloudWatch Logs to OpenSearch Integration for Member Accounts (based on AWS Sample)'

Parameters:
  FirehoseDeliveryStreamArn:
    Type: String
    Description: ARN of the Firehose delivery stream in the management account
    
  ManagementAccountId:
    Type: String
    Description: The AWS account ID of the management account
    
  LogGroupPattern:
    Type: String
    Default: "/aws/lambda/*"
    Description: Pattern(s) for log groups to subscribe (comma-separated list)

  OpenSearchCrossAccountRoleArn:
    Type: String
    Description: ARN of the cross-account role in the management account for OpenSearch access

Resources:
  # IAM role that allows CloudWatch Logs to send to the management account Firehose
  CloudWatchLogsToFirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CloudWatchLogsToFirehoseRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: logs.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: FirehoseDeliveryAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - firehose:PutRecord
                  - firehose:PutRecordBatch
                Resource: !Ref FirehoseDeliveryStreamArn
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource: !Ref OpenSearchCrossAccountRoleArn

  # This Lambda discovers and subscribes log groups matching the pattern
  LogGroupSubscriberFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: CloudWatchToFirehoseSubscriber
      Handler: index.handler
      Role: !GetAtt LogGroupSubscriberRole.Arn
      Runtime: python3.9
      Timeout: 300
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          import os
          import logging
          
          logger = logging.getLogger()
          logger.setLevel(logging.INFO)
          
          def handler(event, context):
              try:
                  logger.info('Received event: %s', event)
                  
                  if event['RequestType'] in ['Create', 'Update']:
                      # Get parameters
                      firehose_arn = event['ResourceProperties']['FirehoseArn']
                      log_group_pattern = event['ResourceProperties']['LogGroupPattern']
                      role_arn = event['ResourceProperties']['RoleArn']
                      
                      # Split pattern into list
                      patterns = [p.strip() for p in log_group_pattern.split(',')]
                      
                      # Get CloudWatch Logs client
                      logs = boto3.client('logs')
                      
                      # Get all log groups
                      log_groups = []
                      next_token = None
                      
                      while True:
                          if next_token:
                              response = logs.describe_log_groups(nextToken=next_token)
                          else:
                              response = logs.describe_log_groups()
                          
                          log_groups.extend(response['logGroups'])
                          
                          if 'nextToken' in response:
                              next_token = response['nextToken']
                          else:
                              break
                      
                      # Subscribe matching log groups
                      for log_group in log_groups:
                          log_group_name = log_group['logGroupName']
                          
                          # Check if log group matches any pattern
                          if any(log_group_name.startswith(pattern) for pattern in patterns):
                              logger.info(f"Subscribing log group: {log_group_name}")
                              
                              try:
                                  logs.put_subscription_filter(
                                      logGroupName=log_group_name,
                                      filterName='FirehoseSubscription',
                                      filterPattern='',  # Match all events
                                      destinationArn=firehose_arn,
                                      roleArn=role_arn
                                  )
                              except Exception as e:
                                  logger.error(f"Error subscribing {log_group_name}: {e}")
                      
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
                  
                  elif event['RequestType'] == 'Delete':
                      # Delete subscription filters
                      logs = boto3.client('logs')
                      log_groups = []
                      next_token = None
                      
                      while True:
                          if next_token:
                              response = logs.describe_log_groups(nextToken=next_token)
                          else:
                              response = logs.describe_log_groups()
                          
                          log_groups.extend(response['logGroups'])
                          
                          if 'nextToken' in response:
                              next_token = response['nextToken']
                          else:
                              break
                      
                      for log_group in log_groups:
                          log_group_name = log_group['logGroupName']
                          try:
                              logs.delete_subscription_filter(
                                  logGroupName=log_group_name,
                                  filterName='FirehoseSubscription'
                              )
                          except Exception as e:
                              logger.error(f"Error deleting subscription filter for {log_group_name}: {e}")
                      
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
                      
              except Exception as e:
                  logger.error(f"Error: {e}")
                  cfnresponse.send(event, context, cfnresponse.FAILED, {})

      Environment:
        Variables:
          MANAGEMENT_ACCOUNT_ID: !Ref ManagementAccountId
          OPENSEARCH_ROLE_ARN: !Ref OpenSearchCrossAccountRoleArn

  # IAM role for the Lambda
  LogGroupSubscriberRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: LogSubscriberPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:DescribeLogGroups
                  - logs:PutSubscriptionFilter
                  - logs:DeleteSubscriptionFilter
                  - logs:DescribeSubscriptionFilters
                Resource: '*'
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource: !Ref OpenSearchCrossAccountRoleArn

  # Custom resource to trigger the Lambda function
  SubscribeLogGroups:
    Type: Custom::SubscribeLogGroups
    Properties:
      ServiceToken: !GetAtt LogGroupSubscriberFunction.Arn
      FirehoseArn: !Ref FirehoseDeliveryStreamArn
      LogGroupPattern: !Ref LogGroupPattern
      RoleArn: !GetAtt CloudWatchLogsToFirehoseRole.Arn

  # Schedule to run the Lambda periodically to catch new log groups
  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Name: DiscoverNewLogGroups
      Description: "Run periodically to discover and subscribe new log groups"
      ScheduleExpression: "rate(1 hour)"
      State: ENABLED
      Targets:
        - Arn: !GetAtt LogGroupSubscriberFunction.Arn
          Id: LogGroupSubscriberFunction
          Input: !Sub |
            {
              "RequestType": "Create",
              "ResourceProperties": {
                "FirehoseArn": "${FirehoseDeliveryStreamArn}",
                "LogGroupPattern": "${LogGroupPattern}",
                "RoleArn": "${CloudWatchLogsToFirehoseRole.Arn}"
              }
            }

  # Permission for CloudWatch Events to invoke the Lambda
  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LogGroupSubscriberFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ScheduledRule.Arn

Outputs:
  CloudWatchLogsToFirehoseRoleArn:
    Description: ARN of the IAM role for CloudWatch to access Firehose
    Value: !GetAtt CloudWatchLogsToFirehoseRole.Arn
  
  LogGroupSubscriberFunctionArn:
    Description: ARN of the Lambda function that subscribes log groups
    Value: !GetAtt LogGroupSubscriberFunction.Arn 