# TFE Workspace Provisioning Module
# Pre-provisions Terraform Cloud workspaces for all managed repositories
# Must be applied BEFORE running individual repository stacks
#
# Authentication:
#   Uses TF_API_TOKEN environment variable for BOTH:
#   - Terraform Cloud backend authentication
#   - TFE provider API calls
#   This is the same token - no separate configuration needed.
#
# Usage:
#   export TF_API_TOKEN="your-tfc-token"
#   terragrunt init
#   terragrunt apply
#
# NOTE: terraform/required_providers block is generated by Terragrunt in provider.tf
# Do NOT add required_providers here - it will cause "duplicate required providers" error

variable "organization" {
  type        = string
  description = "Terraform Cloud organization name"
  default     = "jbcom"
}

variable "github_owner" {
  type        = string
  description = "GitHub owner (user or org) for VCS integration"
  default     = "jbdevprimary"
}

variable "github_oauth_token_id" {
  type        = string
  description = "OAuth token ID for GitHub VCS provider in TFC"
  default     = ""
}

variable "repositories" {
  type = map(object({
    language    = string
    description = optional(string, "")
    tags        = optional(list(string), [])
  }))
  description = "Map of repository names to their configuration"
}

variable "default_execution_mode" {
  type        = string
  description = <<-EOT
    Execution mode for workspaces:
    - "local": Terraform runs locally (CLI-driven), TFC only stores state (recommended for this setup)
    - "remote": TFC runs Terraform (requires .tf files in working_directory, not compatible with Terragrunt-only repos)
    - "agent": TFC agent runs Terraform
  EOT
  default     = "local"
  validation {
    condition     = contains(["remote", "local", "agent"], var.default_execution_mode)
    error_message = "Execution mode must be one of: remote, local, agent"
  }
}

variable "auto_apply" {
  type        = bool
  description = "Whether to auto-apply successful plans"
  default     = false
}

variable "allow_destroy_plan" {
  type        = bool
  description = "Whether to allow destroy plans"
  default     = true
}

variable "global_remote_state" {
  type        = bool
  description = "Allow all workspaces to access each other's state"
  default     = true
}

# Data source for the organization
data "tfe_organization" "this" {
  name = var.organization
}

# Create a workspace for each repository
# Ref: https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/workspace
# Note: global_remote_state was moved to tfe_workspace_settings resource (see below)
resource "tfe_workspace" "repo" {
  for_each = var.repositories

  name         = "jbcom-repo-${each.key}"
  organization = data.tfe_organization.this.name
  description  = coalesce(each.value.description, "Repository management for ${each.key}")

  # Execution settings
  execution_mode = var.default_execution_mode
  auto_apply     = var.auto_apply

  # Working directory - each repo has its own terragrunt directory
  # NOTE: This directory only contains terragrunt.hcl, not .tf files
  # For execution_mode = "local", this is informational only
  # For execution_mode = "remote", TFC would expect .tf files here (not compatible with Terragrunt)
  working_directory = "terragrunt-stacks/${each.value.language}/${each.key}"

  # Allow destroy operations
  allow_destroy_plan = var.allow_destroy_plan

  # VCS integration (optional - can be CLI-driven instead)
  dynamic "vcs_repo" {
    for_each = var.github_oauth_token_id != "" ? [1] : []
    content {
      identifier     = "${var.github_owner}/jbcom-control-center"
      oauth_token_id = var.github_oauth_token_id
      branch         = "main"
    }
  }

  # Tags for organization
  tag_names = concat(
    ["managed", "repository", each.value.language],
    each.value.tags
  )

  lifecycle {
    prevent_destroy = true
  }
}

# Workspace settings resource to manage remote state sharing
# Ref: https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/workspace_settings
# Note: global_remote_state was deprecated in tfe_workspace (v0.61.0) and moved here
resource "tfe_workspace_settings" "repo" {
  for_each = var.repositories

  workspace_id = tfe_workspace.repo[each.key].id

  # Enable global remote state sharing
  # Ref: https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/workspace_settings#global_remote_state
  global_remote_state = var.global_remote_state
}

# Create workspace variables for GitHub token (required for all workspaces)
resource "tfe_variable" "github_token" {
  for_each = var.repositories

  key          = "GITHUB_TOKEN"
  value        = "" # Set via TFC UI or API - never in code
  category     = "env"
  sensitive    = true
  workspace_id = tfe_workspace.repo[each.key].id
  description  = "GitHub token for repository operations"

  lifecycle {
    ignore_changes = [value] # Never overwrite the actual token value
  }
}

# Outputs
output "workspace_ids" {
  value = { for k, v in tfe_workspace.repo : k => v.id }
  description = "Map of repository names to workspace IDs"
}

output "workspace_names" {
  value = { for k, v in tfe_workspace.repo : k => v.name }
  description = "Map of repository names to workspace names"
}

output "workspace_urls" {
  value = {
    for k, v in tfe_workspace.repo : k => "https://app.terraform.io/app/${var.organization}/workspaces/${v.name}"
  }
  description = "Map of repository names to workspace URLs"
}
